FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["src/BankFlow.Api/BankFlow.Api.csproj", "src/BankFlow.Api/"]
COPY ["src/BankFlow.Contracts/BankFlow.Contracts.csproj", "src/BankFlow.Contracts/"]

RUN dotnet restore "src/BankFlow.Api/BankFlow.Api.csproj"

COPY . .

WORKDIR "/src/src/BankFlow.Api"
RUN dotnet publish "BankFlow.Api.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore \
    /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BankFlow.Api.dll"]
